from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from app_cameras.models import Camera


HEADER = """###############################################
# Auto-generated by: python manage.py sync_mediamtx
# WebRTC WHEP: http://127.0.0.1:8889/<path>/whep
###############################################

logLevel: info

api: yes
apiAddress: :9997

rtsp: yes
rtspAddress: :8554

webrtc: yes
webrtcAddress: :8889
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

paths:
"""


class Command(BaseCommand):
    help = 'Генерує mediamtx/mediamtx.yml з RTSP-камер у базі'

    def handle(self, *args, **options):
        out = Path(settings.BASE_DIR) / 'mediamtx' / 'mediamtx.yml'
        lines = [HEADER]
        cameras = Camera.objects.filter(source_type=Camera.SourceType.RTSP)
        if not cameras.exists():
            lines.append('  cam1:\n')
            lines.append('    source: rtsp://user:pass@192.168.1.50:554/stream1\n')
            lines.append('    sourceOnDemand: yes\n')
            self.stdout.write(self.style.WARNING('Немає RTSP-камер — записано приклад cam1'))
        else:
            for cam in cameras:
                path = cam.mediamtx_path or str(cam.id)
                lines.append(f'  {path}:\n')
                lines.append(f'    source: {cam.rtsp_url}\n')
                lines.append('    sourceOnDemand: yes\n')
                self.stdout.write(f'+ {path} <- {cam.rtsp_url}')
        out.write_text(''.join(lines), encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(f'Записано {out}'))
