# Generated by Django 6.1.1 on 2026-09-13 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cameras', '0001_initial'),
        ('app_motion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='recordings/')),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('motion', 'Motion'), ('continuous', 'Continuous')], default='motion', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='app_cameras.camera')),
                ('motion_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='app_motion.motionevent')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
