# Generated by Django 6.1.1 on 2026-09-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingStorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclic_overwrite', models.BooleanField(default=True, help_text='Видаляти найстаріші записи при перевищенні ліміту.')),
                ('max_gb', models.FloatField(default=10.0, help_text='Максимальний обсяг записів на сервері (ГБ).')),
                ('retention_days', models.PositiveIntegerField(default=14, help_text='Автовидалення записів старших за N днів (0 = вимкнено).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording_storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recording storage settings',
                'verbose_name_plural': 'Recording storage settings',
            },
        ),
    ]
