# Generated by Django 6.1.1 on 2026-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recordings', '0002_recordingstoragesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('motion', 'Motion'), ('detection', 'AI Detection'), ('continuous', 'Continuous')], default='motion', max_length=20),
        ),
    ]
