# Generated by Django 6.1.1 on 2026-09-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='app_cameras.camera')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
