# Generated by Django 6.1.1 on 2026-09-14 07:42

import app_integration.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', max_length=120)),
                ('bot_username', models.CharField(blank=True, default='', max_length=120)),
                ('bot_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('chat_title', models.CharField(blank=True, default='', max_length=200)),
                ('link_code', models.CharField(db_index=True, default=app_integration.models.generate_link_code, max_length=16)),
                ('webhook_secret', models.CharField(default=app_integration.models.generate_webhook_secret, max_length=64, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('notify_motion', models.BooleanField(default=True)),
                ('notify_camera_offline', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram integration',
                'verbose_name_plural': 'Telegram integrations',
            },
        ),
    ]
