# Generated by Django 6.1.1 on 2026-09-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0001_initial'),
        ('app_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramintegration',
            name='cameras',
            field=models.ManyToManyField(blank=True, help_text='Камери для сповіщень (якщо не «усі»).', related_name='telegram_integrations', to='app_cameras.camera'),
        ),
        migrations.AddField(
            model_name='telegramintegration',
            name='image_max_width',
            field=models.PositiveIntegerField(default=1280, help_text='Максимальна ширина скріна в пікселях.'),
        ),
        migrations.AddField(
            model_name='telegramintegration',
            name='image_quality',
            field=models.PositiveSmallIntegerField(default=70, help_text='JPEG якість для Telegram (10–95).'),
        ),
        migrations.AddField(
            model_name='telegramintegration',
            name='notify_all_cameras',
            field=models.BooleanField(default=True, help_text='Якщо увімкнено — сповіщення з усіх камер; інакше лише вибрані.'),
        ),
        migrations.AddField(
            model_name='telegramintegration',
            name='send_screenshot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramintegration',
            name='send_video_link',
            field=models.BooleanField(default=True),
        ),
    ]
