"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-k)yjdupc5x!f#3)z=-rr^#3!n+)sreerkhp9cbl0#4#zk5lm*_',
)

DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://10.1.10.123:8007,http://10.1.10.123:8007,https://127.0.0.1:8007,http://127.0.0.1:8007',
    ).split(',')
    if origin.strip()
]

APP_PREFIX = 'app_'

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'config',
    'app_accounts',
    'app_cameras',
    'app_streaming.apps.AppStreamingConfig',
    'app_viewer',
    'app_motion',
    'app_recordings',
    'app_integration.apps.AppIntegrationConfig',
    'app_analytics.apps.AppAnalyticsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.static_bust',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

# Single Daphne process — in-memory signaling is reliable and avoids Redis pub/sub timeouts.
# Set CHANNEL_LAYER=redis in .env to use Redis (multi-worker).
_channel_backend = os.getenv('CHANNEL_LAYER', 'memory').lower()
if _channel_backend == 'redis':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
                'capacity': 1500,
                'expiry': 60,
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'homeboard'),
        'USER': os.getenv('DB_USER', 'homeboard'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'uk'
TIME_ZONE = 'Europe/Kyiv'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'viewer:index'
LOGOUT_REDIRECT_URL = 'accounts:login'

MEDIAMTX_WEBRTC_URL = os.getenv('MEDIAMTX_WEBRTC_URL', 'http://127.0.0.1:8889')
RECORDING_RETENTION_DAYS = int(os.getenv('RECORDING_RETENTION_DAYS', '14'))
RECORDING_MAX_GB = float(os.getenv('RECORDING_MAX_GB', '10'))

# Optional TURN for WebRTC when phone/PC are on different NATs (comma-separated URLs).
# Example: turn:turn.example.com:3478,turns:turn.example.com:5349
_turn_urls = [u.strip() for u in os.getenv('TURN_URLS', '').split(',') if u.strip()]
_turn_user = os.getenv('TURN_USERNAME', '')
_turn_pass = os.getenv('TURN_CREDENTIAL', '')
WEBRTC_ICE_SERVERS = [
    {'urls': 'stun:stun.l.google.com:19302'},
    {'urls': 'stun:stun1.l.google.com:19302'},
]
if _turn_urls:
    turn_entry = {'urls': _turn_urls}
    if _turn_user:
        turn_entry['username'] = _turn_user
        turn_entry['credential'] = _turn_pass
    WEBRTC_ICE_SERVERS.append(turn_entry)
else:
    # Public Open Relay TURN — Chromium often fails LAN P2P (mDNS host candidates).
    # Override with TURN_URLS / TURN_USERNAME / TURN_CREDENTIAL for production.
    WEBRTC_ICE_SERVERS.extend([
        {'urls': 'stun:openrelay.metered.ca:80'},
        {
            'urls': [
                'turn:openrelay.metered.ca:80',
                'turn:openrelay.metered.ca:443',
                'turn:openrelay.metered.ca:443?transport=tcp',
            ],
            'username': 'openrelayproject',
            'credential': 'openrelayproject',
        },
    ])

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# AI analytics (Clearcam-style)
ANALYTICS_DEVICE = os.getenv('ANALYTICS_DEVICE', 'cpu')
ANALYTICS_YOLO_WEIGHTS = os.getenv('ANALYTICS_YOLO_WEIGHTS', str(BASE_DIR / 'models' / 'yolov8n.pt'))
ANALYTICS_IMGSZ = int(os.getenv('ANALYTICS_IMGSZ', '640'))
ANALYTICS_RELAY_URL = os.getenv(
    'ANALYTICS_RELAY_URL',
    'http://127.0.0.1:9011/analytics/api/internal_broadcast/',
)
ANALYTICS_RELAY_SECRET = os.getenv('ANALYTICS_RELAY_SECRET', '') or SECRET_KEY[:32]
OLLAMA_URL = os.getenv('OLLAMA_URL', 'http://127.0.0.1:11434')
OLLAMA_VISION_MODEL = os.getenv('OLLAMA_VISION_MODEL', 'moondream')
OLLAMA_TIMEOUT = float(os.getenv('OLLAMA_TIMEOUT', '300'))
OLLAMA_NUM_PREDICT = int(os.getenv('OLLAMA_NUM_PREDICT', '48'))
