# Generated by Django 6.1.1 on 2026-09-14 09:21

import app_analytics.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cameras', '0001_initial'),
        ('app_motion', '0001_initial'),
        ('app_recordings', '0003_analytics_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('classes', models.JSONField(default=app_analytics.models.default_classes)),
                ('min_confidence', models.FloatField(default=0.45)),
                ('fps', models.FloatField(default=1.0, help_text='Цільовий fps ingest на CPU (0.5–2).')),
                ('zones', models.JSONField(default=app_analytics.models.default_zones)),
                ('phone_assist', models.BooleanField(default=False, help_text='Легка on-device детекція перед upload.')),
                ('summarize', models.BooleanField(default=False, help_text='AI-опис події через Ollama (якщо доступний).')),
                ('trigger_mode', models.CharField(choices=[('motion', 'Після motion/sound'), ('continuous', 'Постійно (низький fps)')], default='motion', max_length=20)),
                ('cooldown_sec', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_settings', to='app_cameras.camera')),
            ],
            options={
                'verbose_name': 'Camera analytics settings',
                'verbose_name_plural': 'Camera analytics settings',
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('classes', models.JSONField(default=list)),
                ('track_ids', models.JSONField(default=list)),
                ('score', models.FloatField(default=0)),
                ('boxes', models.JSONField(default=list)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='analytics/thumbs/')),
                ('summary', models.TextField(blank=True, default='')),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_events', to='app_cameras.camera')),
                ('motion_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='app_motion.motionevent')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='app_recordings.recording')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsFrameJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='analytics/frames/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('source', models.CharField(blank=True, default='motion', max_length=32)),
                ('motion_event_id', models.BigIntegerField(blank=True, null=True)),
                ('phone_hints', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_jobs', to='app_cameras.camera')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='app_analyti_status_4dca0c_idx')],
            },
        ),
    ]
