# Generated by Django 6.1.1 on 2026-09-13 13:43

import app_cameras.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('device_token', models.CharField(default=app_cameras.models.generate_device_token, max_length=64, unique=True)),
                ('source_type', models.CharField(choices=[('browser', 'Browser'), ('rtsp', 'RTSP / IP')], default='browser', max_length=20)),
                ('rtsp_url', models.CharField(blank=True, default='', max_length=500)),
                ('mediamtx_path', models.CharField(blank=True, default='', max_length=120)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=app_cameras.models.generate_pairing_code, max_length=12, unique=True)),
                ('camera_name', models.CharField(default='Camera', max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_origin', to='app_cameras.camera')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expires_at'],
            },
        ),
    ]
